.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "JClic Reports" "1" "diciembre 24, 2007" "" ""
.SH "NAME"
jclicreports \-  Management of a database to track students work and results on JClic activities.
.SH "SYNOPSIS"
.B jclicreports
.RI [ options ] 
.SH "DESCRIPTION"
This manual page documents briefly the
.B jclicreports
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page..
.PP 

\fBJClic\fP is formed by a set of computer applications that are used for carrying out different types of educational activities: puzzles, associations, text exercises, crosswords...
 These activities are  packed in projects. A project is formed by a set of activities and one or more sequences, which indicate the order in which they have to be shown.

 jclicreports allows the management of a database to track
 students work and results after playing JClic activities. It also acts as a server to allow accesing to the data using a web browser.

.SH "OPTIONS"
A summary of options is included below.


.TP 
.B \-trace=true
Show in a terminal some debug information for the application.
.SH "AUTHOR"
JClic was written by <Francesc Busquets>.
.PP 
This manual page was written by José L. Redrejo Rodríguez <jredrejo@edu.juntaextremadura.net>,
for the Debian project (but may be used by others).
